import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header/Header";
import Body from "../components/body/Body";
import Main from "../components/main/Main";
import Footer from "../components/footer/Footer";
import HeroSection from "../components/heroSection/HeroSection";
import ScrollDown from "../components/scrolldown/ScrollDown";
import HeroSectionProjects from "../components/heroSection/HeroSectionProjects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Erik Boye Sørensen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <Header></Header>
        <Main>
          <HeroSection></HeroSection>
          <ScrollDown></ScrollDown>
          <HeroSectionProjects></HeroSectionProjects>
        </Main>
        <Footer></Footer>
      </Body>
    </>
  );
}
